stages:
  - build
  - test
  - deploy

variables:
  yarn_config_cache: "$CI_PROJECT_DIR/.yarn"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
      - package.json
      - yarn.lock
  paths:
    - cache/Cypress
    - node_modules

install:
  image: cypress/base:12.16.1
  stage: build
  script:
    - yarn install --frozen-lockfile --check-files
    - npx cypress cache path
    - npx cypress cache list

eslint-src:
  image: cypress/base:12.16.1
  stage: test
  script:
    - yarn eslint src

eslint-cypress:
  image: cypress/base:12.16.1
  stage: test
  script:
    - yarn eslint cypress

jest:
  image: cypress/base:12.16.1
  stage: test
  script:
    - yarn jest

.cypress_template: &cypress
  image: cypress/base:12.16.1
  stage: test
  script:
    - yarn run dev &
    - yarn cy:run --spec ./cypress/integration/$test_name.js

cy-cards:
  variables:
    test_name: "cards"
  <<: *cypress

cy-coursePage:
  variables:
    test_name: "coursePage"
  <<: *cypress

cy-fanfareScreen:
  variables:
    test_name: "fanfareScreen"
  <<: *cypress

cy-listening:
  variables:
    test_name: "listening"
  <<: *cypress

cy-shortInput:
  variables:
    test_name: "shortInput"
  <<: *cypress

cy-optionSelection:
  variables:
    test_name: "optionSelection"
  <<: *cypress

cy-chips:
  variables:
    test_name: "chips"
  <<: *cypress

deploy-to-gh-pages:
  image: cypress/base:12.16.1
  stage: deploy
  script:
    - NODE_ENV=production yarn export
    - git config --global user.email "gitlab@daniel-kantor.com"
    - git config --global user.name "Dániel Kántor"
    - yarn deploy --repo=https://$GH_TOKEN@github.com/kantord/LibreLingo.git
  only:
    refs:
      - master
