site_name: LibreLingo Documentation
repo_url: https://github.com/kantord/LibreLingo
use_directory_urls: false
theme:
  name: material
  palette:
    primary: #325f74;

plugins:
    - search
    - mermaid2
