[tool.poetry]
name = "librelingo_json_export"
version = "0.1.0"
description = ""
authors = ["Dániel Kántor <git@daniel-kantor.com>"]
license = "AGPLv3"

[tool.poetry.dependencies]
python = "^3.9"
librelingo-types = "^0.1.1"
librelingo-utils = "^0.1.2"
python-slugify = "^4.0.1"
librelingo-tools = "^0.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-watch = "^4.2.0"
pyfakefs = "^4.3.3"
librelingo-fakes = "^0.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
