name: Deployment to production
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '55 * * * *'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        node-version: ["14"]
        os: [ubuntu-20.04]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup git user
        run: |
            git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: snok/install-poetry@v1
      - name: Install Python Dependencies
        shell: bash
        run: poetry install
      - name: validate that Test Course Json files are up to date
        run: |
          poetry install --no-interaction
          cd apps/librelingo_yaml_loader
          poetry install --no-interaction
          cd ../librelingo_json_export
          poetry install --no-interaction
          cd ../..
          ./scripts/verifyTestCourseJsonFiles.sh
      - name: install node dependencies
        run: yarn install
      - name: statically build entire website
        run: NODE_ENV=production yarn export:production
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: __sapper__/export
          cname: librelingo.app
